OITReporting/Controllers/ClientManagerController.cs
using OITReporting.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OITReporting.Controllers
{
    public class ClientManagerController : Controller
    {
        // GET: ClientManager
        public ActionResult Index()
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            return View(db.clientMasters.ToList());
        }

        [HttpGet]
        public ActionResult addClient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addClient(clientMaster cm)
        {
            if (ModelState.IsValid)
            {
                dbOITReportingEntities db = new dbOITReportingEntities();
                db.clientMasters.Add(cm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.status = "Invalid Request";
            }
            return View();
        }

        [HttpGet]
        public ActionResult editClient(int id)
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            return View(db.clientMasters.Where(n => n.clientId.Equals(id)).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult editClient(clientMaster cm)
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            if (ModelState.IsValid)
            {
                db.Entry(cm).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.status = "Invalid request";
            }
            return View();
        }

        [HttpPost]
        public ActionResult deleteClient(int id, clientMaster cm)
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            var clients = db.clientMasters.Where(n => n.clientId.Equals(id)).FirstOrDefault();
            db.clientMasters.Remove(clients);
            db.SaveChanges();
            return View("Index");
        }
    }
}

OITReporting/Controllers/UserManagerController.cs
using OITReporting.Models;
using OITReporting.Models.dbClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OITReporting.Controllers
{
    [Authorize]
    public class UserManagerController : Controller
    {
        [Authorize]
        // GET: UserManager
        public ActionResult Index()
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            var user = db.userMasters.ToList();
            return View(user);
        }

        [HttpGet]
        public ActionResult addUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addUser(userMaster um)
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            if (ModelState.IsValid)
            { 
                db.userMasters.Add(entity: um);
                db.SaveChanges();
                ViewBag.status = "User is Added";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.status = "Invalid Request";
            }
            return View();
        }
        [HttpGet]
        public ActionResult editUser(int id)
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            var user = db.userMasters.Where(n => n.userId.Equals(id)).FirstOrDefault();
            return View(user);
        }

        [HttpPost]
        public ActionResult editUser(userMaster um)
        {
            dbOITReportingEntities db = new dbOITReportingEntities();
            db.Entry(um).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return View("Index");
        }

        [HttpPost]
        public ActionResult deleteUser()
        {
            return RedirectToAction("Index");
        }
    }
}

OITReporting/Views/ClientManager/Index.cshtml
@model IEnumerable<OITReporting.Models.clientMaster>

@{
    ViewBag.Title = "Index";
}

<div class="inner_content">
    <!-- /inner_content_w3_agile_info-->
    <!-- breadcrumbs -->
    <div class="w3l_agileits_breadcrumbs">
        <div class="w3l_agileits_breadcrumbs_inner">
            <ul>
                <li><a href="~/Home/Dashboard">Home</a><span>«</span></li>
                <li><a href="~/ClientManager/Index">Manage Client</a></li>
            </ul>
        </div>
    </div>
    <br />
    <div>
        <h2 class="text-info text-center text-uppercase">List of Cleints</h2>
    </div>
    @*<div>
            @Html.ActionLink("New User","addUser", "UserManager")
        </div>*@
    <div>
        <a href="~/ClientManager/addClient" class="btn btn-primary">Add Client</a>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.emailId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.companyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactPersonName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.contactPersonContactNo1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.city)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isResponded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isUnsubscribe)
            </th>
            <th>
                <strong>Action</strong>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.emailId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.companyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactPersonName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.contactPersonContactNo1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isResponded)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isUnsubscribe)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.clientId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.clientId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.clientId })
                </td>
            </tr>
        }

    </table>
</div>